import pytest
from pydantic import BaseModel, Field
from typing import Literal, Optional


# ============================================================================
# CONTRACT DEFINITIONS
# ============================================================================

# 1. Rahul's Platform Service Contract: /api/v1/auth/verify
class PlatformVerifyContractResponse(BaseModel):
    valid: bool
    user_id: int
    email: str
    full_name: Optional[str] = None
    role: Optional[str] = None
    supplier_id: Optional[str] = None
    is_active: Optional[bool] = True
    permissions: list[str] = Field(default_factory=list)


# 2. Geethika's Compliance Service Contract: /api/v1/compliance/internal-check
class ComplianceCheckContractRequest(BaseModel):
    supplier_id: str
    supplier_name: str
    country: str


class ComplianceCheckContractResponse(BaseModel):
    cleared: bool
    decision: Literal["CLEAR", "BLOCK", "REVIEW"]
    reason: str


# ============================================================================
# CONTRACT TESTS
# ============================================================================

def test_platform_auth_verify_contract_shape():
    """
    Contract test for Rahul's /verify endpoint.
    Proves that the request generated by inventory auth and the response
    schema expected by inventory strictly conform to Platform's contract.
    """
    valid_payload = {
        "valid": True,
        "user_id": 42,
        "email": "warehouse@example.com",
        "full_name": "Warehouse Manager",
        "role": "warehouse_manager",
        "supplier_id": None,
        "is_active": True,
        "permissions": ["inventory:read", "inventory:write"],
    }

    contract = PlatformVerifyContractResponse(**valid_payload)
    assert contract.valid is True
    assert contract.role == "warehouse_manager"
    assert "inventory:write" in contract.permissions


def test_platform_auth_verify_rejection_contract():
    """
    Contract test proving that invalid responses (valid: False or missing permissions)
    are strictly rejected.
    """
    invalid_payload = {
        "valid": False,
        "user_id": 0,
        "email": "invalid@example.com",
        "full_name": "",
        "role": None,
        "permissions": [],
    }

    contract = PlatformVerifyContractResponse(**invalid_payload)
    assert contract.valid is False


def test_compliance_internal_check_request_contract():
    """
    Contract test for Geethika's /internal-check endpoint request shape.
    Proves that request payload matches the required contract.
    """
    req = ComplianceCheckContractRequest(
        supplier_id="SUP-001",
        supplier_name="Global Fasteners Inc",
        country="India",
    )
    assert req.supplier_id == "SUP-001"
    assert req.supplier_name == "Global Fasteners Inc"
    assert req.country == "India"


def test_compliance_internal_check_response_contract_decisions():
    """
    Contract test for Geethika's /internal-check endpoint response shape.
    Proves that all possible decisions (CLEAR, BLOCK, REVIEW) conform to schema.
    """
    clear_resp = ComplianceCheckContractResponse(
        cleared=True,
        decision="CLEAR",
        reason="Supplier cleared all sanctions lists",
    )
    assert clear_resp.cleared is True
    assert clear_resp.decision == "CLEAR"

    block_resp = ComplianceCheckContractResponse(
        cleared=False,
        decision="BLOCK",
        reason="Supplier is on OFAC sanctions list",
    )
    assert block_resp.cleared is False
    assert block_resp.decision == "BLOCK"

    review_resp = ComplianceCheckContractResponse(
        cleared=False,
        decision="REVIEW",
        reason="Fuzzy match found on PEP list",
    )
    assert review_resp.cleared is False
    assert review_resp.decision == "REVIEW"


def test_compliance_internal_check_invalid_decision_fails_contract():
    """
    Contract test: invalid decision values must be rejected by Pydantic validation.
    """
    with pytest.raises(Exception):
        ComplianceCheckContractResponse(
            cleared=True,
            decision="APPROVED",
            reason="Invalid enum value",
        )
