from datetime import date
from typing import List
from enum import Enum

from pydantic import BaseModel, ConfigDict, Field


# ============================================================
# INVOICE STATUS
# ============================================================

class InvoiceStatus(str, Enum):
    submitted = "submitted"
    approved = "approved"
    disputed = "disputed"
    adjusted = "adjusted"
    rejected = "rejected"


# ============================================================
# DISPUTE INFORMATION
# ============================================================

class InvoiceDispute(BaseModel):
    """
    Stores information about an invoice dispute.
    """

    reason: str

    # Person who created the dispute
    actor_id: str
    actor_name: str
    role: str

    # Generated by backend
    timestamp: str

    # Filled when dispute is resolved
    resolution: str | None = None
    resolved_by: str | None = None
    resolved_at: str | None = None


# ============================================================
# INVOICE LINE ITEM
# ============================================================

class InvoiceLineItem(BaseModel):
    """
    Represents one invoice line item.

    Each line item is linked to a specific Purchase Order
    and a specific item within that Purchase Order.
    """

    po_number: str = Field(
        pattern=r"^[A-Za-z0-9_-]+$"
    )

    item_code: str = Field(
        pattern=r"^[A-Za-z0-9_-]+$"
    )

    description: str

    quantity: int = Field(
        gt=0
    )

    unit_price: float = Field(
        gt=0
    )


# ============================================================
# CREATE INVOICE
# ============================================================

class InvoiceCreate(BaseModel):

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "invoice_number": "INV1001",
                "supplier_id": "SUP001",
                "items": [
                    {
                        "po_number": "PO1001",
                        "item_code": "LAP001",
                        "description": "Laptop",
                        "quantity": 5,
                        "unit_price": 50000
                    }
                ],
                "amount": 250000,
                "invoice_date": "2026-08-06"
            }
        }
    )

    invoice_number: str = Field(
        pattern=r"^[A-Za-z0-9_-]+$"
    )

    supplier_id: str = Field(
        pattern=r"^[A-Za-z0-9_-]+$"
    )

    items: List[InvoiceLineItem] = Field(
        min_length=1
    )

    amount: float = Field(
        gt=0
    )

    invoice_date: date


# ============================================================
# ADJUSTMENT REQUEST
# ============================================================

class InvoiceAdjustment(BaseModel):
    """
    Request used to adjust a disputed invoice.

    This changes the actual invoice data and moves:

        disputed -> adjusted
    """

    actor_id: str
    actor_name: str
    role: str

    items: List[InvoiceLineItem] = Field(
        min_length=1
    )

    reason: str

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "actor_id": "usr_002",
                "actor_name": "Rahul",
                "role": "manager",
                "items": [
                    {
                        "po_number": "PO1001",
                        "item_code": "LAP001",
                        "description": "Laptop",
                        "quantity": 5,
                        "unit_price": 48000
                    }
                ],
                "reason": "Corrected unit price according to PO"
            }
        }
    )


# ============================================================
# ADJUSTMENT AUDIT
# ============================================================

class InvoiceAdjustmentAudit(BaseModel):
    """
    Stores what was changed during an invoice adjustment.
    """

    actor_id: str
    actor_name: str
    role: str

    reason: str
    timestamp: str

    old_amount: float
    new_amount: float

    old_items: List[InvoiceLineItem]
    new_items: List[InvoiceLineItem]

# ============================================================
# INVOICE STATUS HISTORY
# ============================================================

class InvoiceHistory(BaseModel):
    """
    Stores the complete status transition history
    of an invoice.
    """

    from_status: InvoiceStatus | None = None
    to_status: InvoiceStatus

    actor_id: str | None = None
    actor_name: str | None = None
    role: str | None = None

    reason: str | None = None

    timestamp: str


# ============================================================
# INVOICE RESPONSE
# ============================================================

class InvoiceResponse(BaseModel):

    invoice_number: str

    supplier_id: str

    items: List[InvoiceLineItem]

    amount: float

    invoice_date: date

    status: InvoiceStatus = InvoiceStatus.submitted

    dispute: InvoiceDispute | None = None

    adjustment: InvoiceAdjustmentAudit | None = None

    document_url: str | None = None

    # NEW
    history: List[InvoiceHistory] = Field(
       default_factory=list
   )


# ============================================================
# NORMAL STATUS TRANSITION REQUEST
# ============================================================

class InvoiceTransition(BaseModel):

    target_state: InvoiceStatus

    actor_id: str
    actor_name: str
    role: str

    reason: str | None = None


class OrphanedInvoiceFile(BaseModel):
    invoice_number: str
    supplier_id: str
    file_path: str
    file_name: str
    size_bytes: int


class OrphanedFileCleanupResponse(BaseModel):
    total: int
    orphaned_files: List[OrphanedInvoiceFile]


class OrphanedFilePurgeResponse(BaseModel):
    total: int
    deleted: int
    files: List[OrphanedInvoiceFile]