"""
Round 10 Locust sweep.

Runs each concurrency level, samples the gateway process's CPU while it runs,
and writes load_tests/round10_summary.md DIRECTLY from the Locust CSVs, so
every number in the report can be regenerated by re-running this script.

Before running:
  1. python dummy_services.py                      (terminal 1)
  2. $env:LOAD_TEST_MODE="true"                    (terminal 2: all Locust users
     uvicorn app.main:app --host 127.0.0.1 --port 8000     share one IP, so rate
                                                           limits would only measure 429s)
     Do NOT use --reload (it spawns a child process with a different PID).
  3. Find the gateway PID (PowerShell):
       (Get-NetTCPConnection -LocalPort 8000 -State Listen).OwningProcess

Usage:
  python run_locust_sweep.py --gateway-pid <PID>
"""

import argparse
import csv
import statistics
import subprocess
import sys
import threading
import time
from pathlib import Path

import psutil  # installed with locust

GATEWAY_DIR = Path(__file__).resolve().parent
LOAD_DIR = GATEWAY_DIR / "load_tests"
SUMMARY_FILE = LOAD_DIR / "round10_summary.md"

HOST = "http://127.0.0.1:8000"
RUN_TIME = "60s"
CONCURRENCIES = [5, 10, 20, 50, 100, 150, 200]

# A level is "degraded" if either is true. Stop after the first degraded level.
DEGRADED_P95_MS = 1000.0
DEGRADED_ERROR_PCT = 1.0


def sample_cpu(pid: int, stop: threading.Event, samples: list[float]) -> None:
    proc = psutil.Process(pid)
    proc.cpu_percent(None)  # first call primes the counter
    while not stop.is_set():
        time.sleep(1.0)
        samples.append(proc.cpu_percent(None))


def aggregated_row(users: int) -> dict:
    stats_file = LOAD_DIR / f"round10_results_u{users}_stats.csv"
    with stats_file.open(newline="", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            if row["Name"] == "Aggregated":
                requests = int(row["Request Count"])
                failures = int(row["Failure Count"])
                return {
                    "users": users,
                    "requests": requests,
                    "rps": float(row["Requests/s"]),
                    "error_pct": (failures / requests * 100.0) if requests else 0.0,
                    "p50": float(row["50%"]),
                    "p95": float(row["95%"]),
                    "p99": float(row["99%"]),
                    "max": float(row["Max Response Time"]),
                }
    raise SystemExit(f"No Aggregated row in {stats_file}")


def run_level(users: int, gateway_pid: int) -> dict:
    print(f"\n=== {users} users for {RUN_TIME} ===")
    samples: list[float] = []
    stop = threading.Event()
    sampler = threading.Thread(
        target=sample_cpu, args=(gateway_pid, stop, samples), daemon=True
    )
    sampler.start()

    cmd = [
        sys.executable, "-m", "locust",
        "-f", "load_tests/round10_locustfile.py",
        "--headless",
        "--users", str(users),
        "--spawn-rate", str(max(2, users // 5)),
        "--run-time", RUN_TIME,
        "--host", HOST,
        "--csv", f"load_tests/round10_results_u{users}",
    ]
    proc = subprocess.run(cmd, cwd=GATEWAY_DIR, capture_output=True, text=True)

    stop.set()
    sampler.join()

    # Locust exits 1 when any request failed; that's data, not a crash.
    if proc.returncode not in (0, 1):
        raise SystemExit(f"Locust crashed at {users} users:\n{proc.stderr}")

    row = aggregated_row(users)
    row["cpu_avg"] = statistics.mean(samples) if samples else 0.0
    row["cpu_max"] = max(samples) if samples else 0.0
    row["degraded"] = (
        row["p95"] > DEGRADED_P95_MS or row["error_pct"] > DEGRADED_ERROR_PCT
    )
    return row


def write_summary(rows: list[dict]) -> None:
    lines = [
        "<!-- GENERATED by run_locust_sweep.py from round10_results_u*_stats.csv. Do not edit by hand. -->",
        "",
        f"Run time per level: {RUN_TIME}. Degraded = p95 > {DEGRADED_P95_MS:.0f} ms "
        f"or error rate > {DEGRADED_ERROR_PCT:.0f} %.",
        "",
        "| Users | Requests | RPS | Error % | p50 (ms) | p95 (ms) | p99 (ms) | Max (ms) "
        "| Gateway CPU avg % | Gateway CPU max % | Status |",
        "|---|---|---|---|---|---|---|---|---|---|---|",
    ]
    for r in rows:
        lines.append(
            f"| {r['users']} | {r['requests']} | {r['rps']:.2f} | {r['error_pct']:.2f} "
            f"| {r['p50']:.0f} | {r['p95']:.0f} | {r['p99']:.0f} | {r['max']:.0f} "
            f"| {r['cpu_avg']:.0f} | {r['cpu_max']:.0f} "
            f"| {'DEGRADED' if r['degraded'] else 'OK'} |"
        )
    SUMMARY_FILE.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"\nWrote {SUMMARY_FILE}")
    print("\n".join(lines))


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--gateway-pid", type=int, required=True)
    args = parser.parse_args()

    rows = []
    for users in CONCURRENCIES:
        row = run_level(users, args.gateway_pid)
        rows.append(row)
        if row["degraded"]:
            print(f"Degraded at {users} users; stopping the ramp here.")
            break
        time.sleep(5)  # let the gateway settle between levels

    write_summary(rows)


if __name__ == "__main__":
    main()
