-- Safe migration for an existing, unpartitioned sales_fact.
-- Preserves row IDs so sales_fact_history remains valid. Run once during a maintenance window.
BEGIN;

DO $$
DECLARE
    is_partitioned boolean;
    min_date date;
    max_date date;
    cursor_date date;
    next_date date;
    partition_name text;
BEGIN
    SELECT EXISTS (
        SELECT 1 FROM pg_partitioned_table pt
        JOIN pg_class c ON c.oid = pt.partrelid
        WHERE c.relname = 'sales_fact'
    ) INTO is_partitioned;

    IF NOT EXISTS (SELECT 1 FROM pg_class WHERE relname='sales_fact' AND relkind='r') THEN
        RAISE NOTICE 'sales_fact does not exist; fresh schema will create it.';
        RETURN;
    END IF;

    IF is_partitioned THEN
        RAISE NOTICE 'sales_fact is already partitioned; nothing to migrate.';
        RETURN;
    END IF;

    SELECT MIN(date), MAX(date) INTO min_date, max_date FROM sales_fact;
    ALTER TABLE sales_fact RENAME TO sales_fact_unpartitioned_backup;

    CREATE TABLE sales_fact (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY,
        date DATE NOT NULL,
        sku_id VARCHAR(50) NOT NULL,
        warehouse_id VARCHAR(20) NOT NULL,
        quantity_sold INTEGER,
        unit_price NUMERIC(12,2),
        source_batch VARCHAR(100),
        run_id BIGINT,
        pipeline_version VARCHAR(20),
        loaded_at TIMESTAMP DEFAULT NOW(),
        updated_at TIMESTAMP DEFAULT NOW(),
        PRIMARY KEY (date, id),
        UNIQUE(date, sku_id, warehouse_id)
    ) PARTITION BY RANGE (date);

    IF min_date IS NULL THEN
        CREATE TABLE sales_fact_default PARTITION OF sales_fact DEFAULT;
    ELSE
        cursor_date := date_trunc('month', min_date)::date;
        max_date := (date_trunc('month', max_date) + interval '1 month')::date;
        WHILE cursor_date < max_date LOOP
            next_date := (cursor_date + interval '1 month')::date;
            partition_name := format('sales_fact_%s', to_char(cursor_date, 'YYYY_MM'));
            EXECUTE format(
                'CREATE TABLE %I PARTITION OF sales_fact FOR VALUES FROM (%L) TO (%L)',
                partition_name, cursor_date, next_date
            );
            cursor_date := next_date;
        END LOOP;
        CREATE TABLE sales_fact_default PARTITION OF sales_fact DEFAULT;
    END IF;

    INSERT INTO sales_fact
        (id, date, sku_id, warehouse_id, quantity_sold, unit_price, source_batch, run_id, pipeline_version, loaded_at, updated_at)
    SELECT id, date, sku_id, warehouse_id, quantity_sold, unit_price, source_batch, run_id, pipeline_version, loaded_at, updated_at
    FROM sales_fact_unpartitioned_backup;

    PERFORM setval(
        pg_get_serial_sequence('sales_fact', 'id'),
        COALESCE((SELECT MAX(id) FROM sales_fact), 1),
        true
    );

    DROP TABLE sales_fact_unpartitioned_backup;
    RAISE NOTICE 'sales_fact migrated to monthly partitions.';
END $$;

COMMIT;
