import pandas as pd

from src.feature_usefulness import (
    calculate_feature_correlations,
    calculate_model_feature_importance,
    select_top_features,
)
from src.build_features import build_all_features


URL = "https://raw.githubusercontent.com/facebook/prophet/main/examples/example_retail_sales.csv"


def main():

    # Load the public retail sales dataset.
    df = pd.read_csv(URL)

    # Rename the dataset columns to match our library interface.
    df = df.rename(
        columns={
            "ds": "date",
            "y": "quantity_sold"
        }
    )

    # Convert the date column to datetime.
    df["date"] = pd.to_datetime(df["date"])

    # First configuration with 1, 7, and 30-day lags
    # and 7 and 30-day rolling windows.
    config_1 = {
        "lags": [1, 7, 30],
        "windows": [7, 30]
    }

    # Build features using the first configuration.
    result_1 = build_all_features(
        df,
        date_col="date",
        target_col="quantity_sold",
        config=config_1
    )

    # Second configuration with different lag and
    # rolling-window values.
    config_2 = {
        "lags": [1, 7, 14],
        "windows": [7, 14]
    }

    # Build features using the second configuration.
    result_2 = build_all_features(
        df,
        date_col="date",
        target_col="quantity_sold",
        config=config_2
    )

    # Display the feature columns generated by each configuration.
    print("Features with config 1:")
    print(result_1.columns.tolist())

    print("\nFeatures with config 2:")
    print(result_2.columns.tolist())

    # Calculate feature correlations for configuration 1.
    correlations_1 = calculate_feature_correlations(
        result_1,
        target_col="quantity_sold"
    )

    # Calculate model-based feature importance for configuration 1.
    importance_1 = calculate_model_feature_importance(
        result_1,
        target_col="quantity_sold"
    )

    # Select the top 5 useful features using both
    # correlation and model-based importance.
    selected_features_1 = select_top_features(
        result_1,
        target_col="quantity_sold",
        n_features=5
    )

    # Display the first 10 rows generated by configuration 1.
    print("\nFirst 10 rows with config 1:")
    print(result_1.head(10))

    # Display the first 10 rows generated by configuration 2.
    print("\nFirst 10 rows with config 2:")
    print(result_2.head(10))

    # Display feature correlations for configuration 1.
    print("\nFeature correlations with target - config 1:")
    print(correlations_1)

    # Display model-based feature importance for configuration 1.
    print("\nModel-based feature importance - config 1:")
    print(importance_1)

    # Display the top 5 selected features.
    print("\nTop 5 selected features - config 1:")
    print(selected_features_1)

    # Show how feature selection reduces the candidate feature set.
    candidate_feature_count = (
        len(result_1.select_dtypes(include="number").columns) - 1
    )

    print(
        "\nNumber of candidate features:",
        candidate_feature_count
    )

    print(
        "Number of selected features:",
        len(selected_features_1)
    )


if __name__ == "__main__":
    main()