"""create compliance tables

Revision ID: ad1be0670cf4
Revises: 
Create Date: 2026-09-30 14:05:20.357240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad1be0670cf4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compliance_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_name', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('matched', sa.Boolean(), nullable=False),
    sa.Column('matched_name', sa.String(), nullable=True),
    sa.Column('matched_lists', sa.String(), nullable=True),
    sa.Column('match_score', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_factors', sa.Text(), nullable=True),
    sa.Column('country_risk_score', sa.Float(), nullable=False),
    sa.Column('overall_supplier_risk', sa.Float(), nullable=False),
    sa.Column('screening_type', sa.String(), nullable=False),
    sa.Column('newly_flagged', sa.Boolean(), nullable=False),
    sa.Column('screening_run_id', sa.String(), nullable=True),
    sa.Column('service_name', sa.String(), nullable=False),
    sa.Column('duration_ms', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_country', 'compliance_audit', ['country'], unique=False)
    op.create_index('idx_audit_entity_date', 'compliance_audit', ['entity_name', 'created_at'], unique=False)
    op.create_index('idx_audit_newly_flagged_date', 'compliance_audit', ['newly_flagged', 'created_at'], unique=False)
    op.create_index('idx_audit_screening_run', 'compliance_audit', ['screening_run_id'], unique=False)
    op.create_index('idx_audit_screening_type_date', 'compliance_audit', ['screening_type', 'created_at'], unique=False)
    op.create_index(op.f('ix_compliance_audit_country'), 'compliance_audit', ['country'], unique=False)
    op.create_index(op.f('ix_compliance_audit_created_at'), 'compliance_audit', ['created_at'], unique=False)
    op.create_index(op.f('ix_compliance_audit_entity_name'), 'compliance_audit', ['entity_name'], unique=False)
    op.create_index(op.f('ix_compliance_audit_id'), 'compliance_audit', ['id'], unique=False)
    op.create_index(op.f('ix_compliance_audit_newly_flagged'), 'compliance_audit', ['newly_flagged'], unique=False)
    op.create_index(op.f('ix_compliance_audit_screening_run_id'), 'compliance_audit', ['screening_run_id'], unique=False)
    op.create_index(op.f('ix_compliance_audit_screening_type'), 'compliance_audit', ['screening_type'], unique=False)
    op.create_table('compliance_case',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_number', sa.String(), nullable=False),
    sa.Column('entity_name', sa.String(), nullable=False),
    sa.Column('normalized_entity_name', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('matched_name', sa.String(), nullable=True),
    sa.Column('matched_lists', sa.String(), nullable=True),
    sa.Column('match_score', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('screening_tier', sa.String(), nullable=True),
    sa.Column('screening_action', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('assigned_to', sa.String(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution', sa.String(), nullable=True),
    sa.Column('resolution_reason', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_case_assigned_to'), 'compliance_case', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_compliance_case_case_number'), 'compliance_case', ['case_number'], unique=True)
    op.create_index(op.f('ix_compliance_case_country'), 'compliance_case', ['country'], unique=False)
    op.create_index(op.f('ix_compliance_case_created_at'), 'compliance_case', ['created_at'], unique=False)
    op.create_index(op.f('ix_compliance_case_entity_name'), 'compliance_case', ['entity_name'], unique=False)
    op.create_index(op.f('ix_compliance_case_id'), 'compliance_case', ['id'], unique=False)
    op.create_index(op.f('ix_compliance_case_normalized_entity_name'), 'compliance_case', ['normalized_entity_name'], unique=False)
    op.create_index(op.f('ix_compliance_case_status'), 'compliance_case', ['status'], unique=False)
    op.create_table('compliance_override',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_name', sa.String(), nullable=False),
    sa.Column('matched_name', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('reviewed_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_override_entity_name'), 'compliance_override', ['entity_name'], unique=False)
    op.create_index(op.f('ix_compliance_override_id'), 'compliance_override', ['id'], unique=False)
    op.create_index(op.f('ix_compliance_override_matched_name'), 'compliance_override', ['matched_name'], unique=False)
    op.create_index(op.f('ix_compliance_override_source'), 'compliance_override', ['source'], unique=False)
    op.create_table('regulatory_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_code', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('rule_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regulatory_rules_country'), 'regulatory_rules', ['country'], unique=False)
    op.create_index(op.f('ix_regulatory_rules_id'), 'regulatory_rules', ['id'], unique=False)
    op.create_index(op.f('ix_regulatory_rules_rule_code'), 'regulatory_rules', ['rule_code'], unique=True)
    op.create_table('case_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.String(), nullable=True),
    sa.Column('to_status', sa.String(), nullable=False),
    sa.Column('changed_by', sa.String(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['compliance_case.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_history_case_id'), 'case_history', ['case_id'], unique=False)
    op.create_index(op.f('ix_case_history_changed_at'), 'case_history', ['changed_at'], unique=False)
    op.create_index(op.f('ix_case_history_id'), 'case_history', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_case_history_id'), table_name='case_history')
    op.drop_index(op.f('ix_case_history_changed_at'), table_name='case_history')
    op.drop_index(op.f('ix_case_history_case_id'), table_name='case_history')
    op.drop_table('case_history')
    op.drop_index(op.f('ix_regulatory_rules_rule_code'), table_name='regulatory_rules')
    op.drop_index(op.f('ix_regulatory_rules_id'), table_name='regulatory_rules')
    op.drop_index(op.f('ix_regulatory_rules_country'), table_name='regulatory_rules')
    op.drop_table('regulatory_rules')
    op.drop_index(op.f('ix_compliance_override_source'), table_name='compliance_override')
    op.drop_index(op.f('ix_compliance_override_matched_name'), table_name='compliance_override')
    op.drop_index(op.f('ix_compliance_override_id'), table_name='compliance_override')
    op.drop_index(op.f('ix_compliance_override_entity_name'), table_name='compliance_override')
    op.drop_table('compliance_override')
    op.drop_index(op.f('ix_compliance_case_status'), table_name='compliance_case')
    op.drop_index(op.f('ix_compliance_case_normalized_entity_name'), table_name='compliance_case')
    op.drop_index(op.f('ix_compliance_case_id'), table_name='compliance_case')
    op.drop_index(op.f('ix_compliance_case_entity_name'), table_name='compliance_case')
    op.drop_index(op.f('ix_compliance_case_created_at'), table_name='compliance_case')
    op.drop_index(op.f('ix_compliance_case_country'), table_name='compliance_case')
    op.drop_index(op.f('ix_compliance_case_case_number'), table_name='compliance_case')
    op.drop_index(op.f('ix_compliance_case_assigned_to'), table_name='compliance_case')
    op.drop_table('compliance_case')
    op.drop_index(op.f('ix_compliance_audit_screening_type'), table_name='compliance_audit')
    op.drop_index(op.f('ix_compliance_audit_screening_run_id'), table_name='compliance_audit')
    op.drop_index(op.f('ix_compliance_audit_newly_flagged'), table_name='compliance_audit')
    op.drop_index(op.f('ix_compliance_audit_id'), table_name='compliance_audit')
    op.drop_index(op.f('ix_compliance_audit_entity_name'), table_name='compliance_audit')
    op.drop_index(op.f('ix_compliance_audit_created_at'), table_name='compliance_audit')
    op.drop_index(op.f('ix_compliance_audit_country'), table_name='compliance_audit')
    op.drop_index('idx_audit_screening_type_date', table_name='compliance_audit')
    op.drop_index('idx_audit_screening_run', table_name='compliance_audit')
    op.drop_index('idx_audit_newly_flagged_date', table_name='compliance_audit')
    op.drop_index('idx_audit_entity_date', table_name='compliance_audit')
    op.drop_index('idx_audit_country', table_name='compliance_audit')
    op.drop_table('compliance_audit')
    # ### end Alembic commands ###
