from pathlib import Path

import pandas as pd
from pandas.testing import assert_frame_equal

from src.data import (
    generate_normal_data,
    inject_temperature_drift,
)

project_root = Path(__file__).resolve().parent.parent
output_dir = project_root / "output"


def test_temperature_drift_reproducibility():
    """
    Verify that the temperature drift dataset generated by the
    data pipeline is reproducible when generated independently.

    The comparison uses a floating-point tolerance because CSV
    serialization/deserialization introduces infinitesimally
    small rounding differences.
    """

    # Dataset already prepared by conftest.py
    actual = pd.read_csv(
        output_dir / "test_temperature_drift.csv"
    )

    # Generate the same dataset independently
    normal = generate_normal_data(
        seed=456
    )

    expected = inject_temperature_drift(
        normal,
        hours=24,
        drift_per_hour=0.5,
        seed=1003,
    )

    # Match timestamp dtype
    actual["timestamp"] = pd.to_datetime(
        actual["timestamp"]
    )

    expected["timestamp"] = pd.to_datetime(
        expected["timestamp"]
    )

    # Compare with floating-point tolerance
    assert_frame_equal(
        actual,
        expected,
        check_dtype=False,
        check_exact=False,
        atol=1e-8,
        rtol=1e-8,
    )